### ISSUE TITLE
"background.service_worker is currently disabled"

### ISSUE THREAD

**Issue by NewsGuyTor** [pc035860/YCS-cont#1]
I'm struggling to get this working:
![Skjermbilde 2024-05-31 212154](https://github.com/pc035860/YCS-cont/assets/19603024/82f0e84e-491e-49ef-bc5e-e25b708ed279)

Perhaps this is relevant:
https://stackoverflow.com/questions/75043889/manifest-v3-background-scripts-service-worker-on-firefox

I hope you can create xpi builds, that way people won't have to install a temporary extension.

**Comment by pc035860** [comment]
I see, Firefox is a different build.

**Comment by NewsGuyTor** [comment]
I managed to fix it, the background should be:

   "background": {
      "service_worker": "background.js",
      "scripts": ["background.js"]
   },

**Comment by pc035860** [comment]
@NewsGuyTor I've added the xpi build to the release 👍.

**Comment by NewsGuyTor** [comment]
Awesome! Any plans to upload them to the Firefox/Chrome stores?

**Comment by pc035860** [comment]
> Awesome! Any plans to upload them to the Firefox/Chrome stores?

I'm not the author of the original extension.
I think I'll just leave it as it is for now and see what happens.

**Comment by NewsGuyTor** [comment]
> > Awesome! Any plans to upload them to the Firefox/Chrome stores?
> 
> I'm not the author of the original extension. I think I'll just leave it as it is for now and see what happens.

Why? The original was under MIT, so you are allowed to do whatever, including distributing it:

https://github.com/sonigy/YCS/blob/master/LICENSE

**Comment by pc035860** [comment]
> Why? The original was under MIT, so you are allowed to do whatever, including distributing it:
> 
> https://github.com/sonigy/YCS/blob/master/LICENSE
> 
> You should btw add the MIT license to this fork, that's the only thing required by the MIT license. Added PRs

I mean, not a single line of code from this repository is in the original repository.
Does the license still apply?

**Comment by NewsGuyTor** [comment]
> > Why? The original was under MIT, so you are allowed to do whatever, including distributing it:
> > https://github.com/sonigy/YCS/blob/master/LICENSE
> > You should btw add the MIT license to this fork, that's the only thing required by the MIT license. Added PRs
> 
> I mean, not a single line of code from this repository is in the original repository. Does the license still apply?

Yes, he added the MIT license manually to the [Readme](https://github.com/sonigy/YCS?tab=readme-ov-file#license) for the extension too, so he clearly intended it to apply for the project. 

The Firefox version was uploaded as [Mozilla Public License 2.0](http://www.mozilla.org/MPL/2.0/), that also gives us permission to fork and retribute the fork:
https://addons.mozilla.org/en-US/firefox/addon/ycs/
