### ISSUE TITLE
Encoding bug

### ISSUE THREAD

**Issue by ApusAurelius** [pc035860/YCS-cont#12]
It doesn't work with non-Latin characters.
![11](https://github.com/pc035860/YCS-cont/assets/170759773/82204332-4510-4515-899c-1b282bc47263)

**Comment by pc035860** [comment]
The issue you're experiencing should be resolved in version 1.2.3, specifically in commit 8845c5386c7f7ae500415200f53bb276812986cf. Can you please confirm your current version? If you're already on 1.2.3, you might need to `reload` to update the cache.

**Comment by ApusAurelius** [comment]
Yes, the version was 1.2.2 and installed two days ago. I didn't check update before issue. Now it works. Thank you for fast resolving.
