### ISSUE TITLE
[Feature Request] Browser extension stores

### ISSUE THREAD

**Issue by begin-theadventure** [pc035860/YCS-cont#13]
Firefox Browser Add-ons https://addons.mozilla.org
Chrome Web Store https://chromewebstore.google.com

**Comment by hcgiub001** [comment]
yeah, I think having this on stores with it's own name going forward is best. the original author isn't coming back and for newbies they don't know how to download or do updates

**Comment by spencermacca** [comment]
+1 - would really like to have this automatically update and easy to install functionality. OG project's license allows for it iirc anyway

**Comment by andradadad** [comment]
It would increase visibility.

**Comment by hbouhadji** [comment]
also, is it possible to have an userscript version ? for tampermonkey, violentmonkey etc...

**Comment by pc035860** [comment]
YCS (Continued) is now available on both stores:
- Chrome Web Store: https://chromewebstore.google.com/detail/ycs-youtube-comment-searc/mfobjniokjbcldieppimekoibpocahed
- Firefox Add-ons: https://addons.mozilla.org/zh-TW/firefox/addon/ycs-continued/

**Comment by pc035860** [comment]
> also, is it possible to have an userscript version ? for tampermonkey, violentmonkey etc...

I'll take a look at this, but it may take a while. The extension depends on certain Chrome/Web extension APIs, particularly for caching, so these parts will need to be rewritten.
