### ISSUE TITLE
Does not work after install with .xpi on Firefox fork (Librewolf 127.0-1)

### ISSUE THREAD

**Issue by RenegadeScooter** [pc035860/YCS-cont#17]
I have YCS-cont installed with the **.xpi** file along with the regular YCS on Librewolf 127.0-1 (a fork of Firefox).

For almost all the time I kept it enabled…
- when I have both YCS and YCS-cont enabled, the panel appears but I still can't retrieve comments.
- when I disable YCS but keep YCS-cont enabled, no panel appears.

As of this morning, YCS-cont has only worked once on [this specific video](https://www.youtube.com/watch?v=8zAANBYwA1w) after I went into its options and cleared the cache before refreshing the video page, with both it and regular YCS enabled. Upon reloading, the page lagged before showing the panel with all comments retrieved and 'cached'. I could then search that video's comments like normal. However, it stopped working when I refreshed the page again.

What's going on here? Is YCS-cont supposed to interface with YCS or be a standalone extension? Is there anything I'm missing?

**Comment by pc035860** [comment]
- You only need to enable YCS-cont, a replacement for the outdated YCS extension.
- As Librewolf is a Firefox fork, the issue of "no panel appearing" might be similar to [this one](https://github.com/sonigy/YCS/issues/56#issuecomment-2143693092).
  - Make sure you have `Always Allow on www.youtube.com` checked.

**Comment by RenegadeScooter** [comment]
Oops, I missed that comment. It's working now. Thanks for your help!
The README doesn't mention that permissions issue. Perhaps it should?
