### ISSUE TITLE
TrustedType conflict with other userscript (solved)

### ISSUE THREAD

**Issue by BigBagss** [pc035860/YCS-cont#28]
i used https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass userscript, which adds a TrustedType policy as well, which leads to ycs-cont throwing this error:

```
Uncaught TypeError: Failed to execute 'CreatePolicy' on 'TrustedTypePolicyFactory': Policy with name "default" already exists.
  at wresources.js:16:18
  at wresources.js:13247:3
```

and because of that error, ycs-cont extension doesn't load.

**solution:**
i loaded up ycs-cont manually and added this `if` statement in `wresources.js` to prevent this error from happening:

```
// Trusted Types feature testing
  if (window.trustedTypes && trustedTypes.createPolicy) {
	  if (!trustedTypes.defaultPolicy){
			// provide a default policy for trusted types
			trustedTypes.createPolicy('default', {
			// createHTML() gets called when assigning .innerHTML
			createHTML: (string) => string,
		});
	  }
  }
```
so far i believe it's working well.

apologies if im doing something wrong, i don't really know how to use github etc...
thanks!

**Comment by pc035860** [comment]
Thanks for your report!
The modified version will be in store as version 1.3.3.
