### ISSUE TITLE
Transcription Search

### ISSUE THREAD

**Issue by spencermacca** [pc035860/YCS-cont#5]
Hey,
Thank you so much for fixing this extension! I use it all the time and it's been immensly frustrating with it not working, this is awesome :D
Was wondering if there was any way to get transcript search working as I also like using the extension for this too?

Thanks!

**Comment by drhouse** [comment]
you may find this useful, I wanted to generate subtitles for YouTube videos that didn't have them and found '[transcribe-anything](https://github.com/zackees/transcribe-anything)'.  It quickly auto-generates subtitles/transcriptions in multiple formats:
```
pip install transcribe-anything
# insanely fast using the insanely-fast-whisper backend.
transcribe-anything "https://www.youtube.com/watch?v=yourVideo" --device insane

```

**Comment by spencermacca** [comment]
> you may find this useful, I wanted to generate subtitles for YouTube videos that didn't have them and found '[transcribe-anything](https://github.com/zackees/transcribe-anything)'. It quickly auto-generates subtitles/transcriptions in multiple formats:
> 
> ```
> pip install transcribe-anything
> # insanely fast using the insanely-fast-whisper backend.
> transcribe-anything "https://www.youtube.com/watch?v=yourVideo" --device insane
> ```

Thanks for this! But even on videos where YT has auto-generated captions, it still doesn't work for searching them. I appreciate it nonetheless :)

**Comment by drhouse** [comment]
if you had a generated subtitle .srt file, couldn't you search it using a text application?

**Comment by spencermacca** [comment]
> if you had a generated subtitle .srt file, couldn't you search it using a text application?

No I know. It's more just for a convenience thing. Having the extension right there and if I'm looking for a mention of something in particular takes like 5 seconds because it's built in

**Comment by spencermacca** [comment]
Thank you for fixing @pc035860 ! <3
